Use rpm.files instead of rpm.fi
RPM 4.19 removed a deprecated rpm.fi class in favour of rpm.files:

    # rpmconf -a
    Traceback (most recent call last):
      File "/usr/sbin/rpmconf", line 105, in <module>
        main()
      File "/usr/sbin/rpmconf", line 95, in main
        rconf.run()
      File "/usr/lib/python3.11/site-packages/rpmconf/rpmconf.py", line 122, in run
        tested_files += self._handle_package(pkg_hdr)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/rpmconf/rpmconf.py", line 346, in _handle_package
        for conf_file in self.get_list_of_config(package):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/rpmconf/rpmconf.py", line 159, in get_list_of_config
        files = rpm.fi(package) # pylint: disable=no-member
                ^^^^^^
    AttributeError: module 'rpm' has no attribute 'fi'. Did you mean: 'fd'?

This patch fixes it by porting to rpm.files API. According to RPM git
log, the new API is available since 2013. Thus I did not implement any
fallback.